name: Run main.py with input

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install qrcode==8.0
          pip install pillow==11.0.0
          pip install qrcode==8.0

      - name: Provide input
        run: echo "Hello from GitHub Actions!" > input.txt

      - name: Run main.py
        run: python main.py

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: output-image
          path: output.png
